name: Deploy HUGO to Lighthouse

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Hugo
        run: |
          sudo apt-get update
          sudo apt-get install -y hugo

      - name: 生成静态文件
        run: hugo --minify

      - name: 通过 SSH 发送文件
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "public/*"
          target: "/home/ubuntu/test_dir"
